import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Services", description: "Strategy, experience design and custom development shaped around how the business actually works.", alternates: { canonical: "/services" } };
const blocks: string[][] = [["01 / DIGITAL STRATEGY", "Before decoration.", "Clarify the customer journey, business goals, content structure and technical requirements before deciding what the interface should look like."], ["02 / EXPERIENCE DESIGN", "Make the next step obvious.", "Information architecture, responsive interfaces and conversion paths that help people understand, trust and act."], ["03 / CUSTOM DEVELOPMENT", "Custom means custom.", "Purpose-built websites and interactive systems for businesses that have outgrown template-shaped experiences."], ["04 / COMMERCE + BOOKING", "The website should participate.", "Buying, inquiry, reservation and scheduling flows designed around the real customer decision."], ["05 / BUSINESS SYSTEMS", "Connect the storefront to the work.", "Forms, workflows and operational connections that reduce friction behind the public experience."], ["06 / STUDIO SUPPORT", "Launch is not the end.", "Ongoing refinement, maintenance and expansion for digital properties that need to keep evolving."]];
export default function Page() {
 return <main className="destination-page"><div className="site-background" aria-hidden="true"/>
 <header className="case-nav shell"><Link className="logo" href="/"><span className="logo-mark">A.</span><span>HALLIWELL</span></Link><nav className="destination-nav"><Link href="/work">Work</Link><Link href="/services">Services</Link><Link href="/studio">Studio</Link><Link href="/lab">Lab</Link></nav><Link href="/start">Start a project ↗</Link></header>
 <article className="destination-sheet"><section className="destination-hero"><small>WHAT THE STUDIO BUILDS</small><h1>Design with a job to do.</h1><p>Strategy, experience design and custom development shaped around how the business actually works.</p></section>
 <section className="destination-grid">{blocks.map(([label,t,b])=><article key={label+t} className="destination-block"><small>{label}</small><h2>{t}</h2><p>{b}</p></article>)}</section>
 <section className="case-end"><small>NEXT</small><h2>Build something<br/>worth using.</h2><Link className="button button-primary" href="/start">Start a project ↗</Link></section></article></main>;
}