const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const m={exports:{}};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/lab-models.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{module:m,exports:m.exports});
const {stayTotal,tableMinimum,routeService,demoSlots}=m.exports;
assert.equal(stayTotal(240,2,2,false,false),480);
assert.equal(stayTotal(360,3,4,true,true),1320);
assert.throws(()=>stayTotal(240,0,2,false,false));
assert.throws(()=>stayTotal(240,2,5,false,false));
assert.equal(tableMinimum('Lounge',4).fits,true);
assert.equal(tableMinimum('Lounge',6).fits,false);
assert.equal(tableMinimum('Balcony',12).deposit,300);
assert.equal(routeService('Repair','Inside the demo area','Urgent').kind,'urgent');
assert.equal(routeService('Repair','Outside the demo area','Urgent').kind,'area');
assert.equal(routeService('New installation','Inside the demo area','Planning ahead').bookable,true);
assert.equal(demoSlots['Sunday / sample date'].length,0);
console.log('PASS sample stay calculations, table capacity/deposits, service routing, and empty availability.');
