import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Lab", description: "Small interactive systems, prototypes and experiments that demonstrate how A. Halliwell thinks about digital products.", alternates: { canonical: "/lab" } };
const blocks: string[][] = [["BOOKING", "Reservation logic", "Explore how availability, selection and confirmation can become a clear customer journey."], ["COMMERCE", "Package configurator", "Turn a complicated offer into choices people can understand and act on."], ["QUALIFICATION", "Lead flow", "Ask better questions, preserve context and create a useful handoff instead of a dead contact form."], ["MAPS + EVENTS", "Interactive discovery", "Use space, time and context as interface elements instead of burying them in paragraphs."], ["CALCULATORS", "Decision tools", "Translate business questions into transparent, useful interactions without pretending arithmetic is advice."], ["SOMETHING WEIRD", "Permanent experiment slot", "Creative coding and internet objects that exist because memorable digital experiences need room to be strange."]];
export default function Page() {
 return <main className="destination-page"><div className="site-background" aria-hidden="true"/>
 <header className="case-nav shell"><Link className="logo" href="/"><span className="logo-mark">A.</span><span>HALLIWELL</span></Link><nav className="destination-nav"><Link href="/work">Work</Link><Link href="/services">Services</Link><Link href="/studio">Studio</Link><Link href="/lab">Lab</Link></nav><Link href="/start">Start a project ↗</Link></header>
 <article className="destination-sheet"><section className="destination-hero"><small>INTERACTIVE PROOF</small><h1>Don't read the capability list. Use it.</h1><p>Small interactive systems, prototypes and experiments that demonstrate how A. Halliwell thinks about digital products.</p></section>
 <section className="destination-grid">{blocks.map(([label,t,b])=><article key={label+t} className="destination-block"><small>{label}</small><h2>{t}</h2><p>{b}</p></article>)}</section>
 <section className="case-end"><small>NEXT</small><h2>Build something<br/>worth using.</h2><Link className="button button-primary" href="/start">Start a project ↗</Link></section></article></main>;
}