"use client";
import { useState } from "react";

const worlds = [
  {name:"The estate planner",label:"01 / EXPLORE + PLAN",promise:"Turn a beautiful place into a journey people can picture.",skills:["Interactive maps","Conditional journeys","Live capacity rules","Personalized summaries"],production:"Connect your real venue information, availability, tour inquiries, and planning resources to one guided experience."},
  {name:"The object atelier",label:"02 / CONFIGURE + COLLECT",promise:"Let the customer shape the object before it goes in the bag.",skills:["Live product visualization","Variant pricing","Cart state","Custom commerce"],production:"Connect product options to inventory, payment, order records, and fulfillment. The design can be as individual as the product."},
  {name:"The project room",label:"03 / REVIEW + DELIVER",promise:"Give the work behind the website a considered interface.",skills:["File interactions","Approval gates","Workflow state","Client dashboards"],production:"Connect authenticated clients, private storage, agreements, milestones, and notifications. Access rules belong on the server in a commissioned build."},
];
const spaces = [
  {name:"Garden",capacity:120,x:210,y:150,description:"An open-air ceremony framed by gardens. A shorter walk from the arrival court."},
  {name:"Glasshouse",capacity:80,x:410,y:190,description:"An intimate indoor ceremony with a garden outlook. The rain-plan option in this demonstration."},
  {name:"Grand hall",capacity:160,x:315,y:340,description:"Dinner, speeches, and dancing under one roof. The largest gathering space."},
];
function Estate() {
  const [space,setSpace]=useState(0),[guests,setGuests]=useState(70),[rain,setRain]=useState(false),[saved,setSaved]=useState(false);
  const active=spaces[space], fits=guests<=active.capacity, outdoors=space===0;
  const change=(fn:()=>void)=>{fn();setSaved(false)};
  return <div className="lab-estate lab-world-demo">
    <div className="lab-demo-title"><small>AN IMAGINED ESTATE / PLANNING EXPERIENCE</small><h3>A day, <em>mapped out.</em></h3><p>Select a space on the map. Change the guest count. Try a rainy day.</p></div>
    <div className="lab-experience-grid"><div className="lab-map-wrap"><svg viewBox="0 0 600 470" role="img" aria-label="Illustrative estate map showing garden, glasshouse, grand hall, arrival court and a walking path"><defs><pattern id="lab-grass" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M8 10l3-5 3 5M20 24l2-4 2 4" stroke="#94a688" fill="none" opacity=".4"/></pattern></defs><rect width="600" height="470" fill="#dce5d2"/><rect width="600" height="470" fill="url(#lab-grass)"/><path d="M0 370 Q160 240 130 0 M600 65 Q430 40 500 0" stroke="#b8cfd1" strokeWidth="36" fill="none"/><path d="M80 430 Q100 320 210 150 Q325 80 410 190 Q460 320 315 340" stroke="#f7f1df" strokeWidth="18" fill="none"/><path d="M80 430 Q100 320 210 150 Q325 80 410 190 Q460 320 315 340" stroke="#b99a82" strokeDasharray="5 8" strokeWidth="2" fill="none"/><ellipse cx="210" cy="155" rx="85" ry="58" fill="#b4c49b" stroke="#77885e"/><g fill="#f3ddd6" stroke="#947c76" strokeWidth="2"><path d="M355 145h110v80H355zM355 145l55-38 55 38"/><path d="M250 300h130v80H250zM240 300l75-45 75 45"/></g><g fill="#69865d">{[[65,120],[90,200],[500,300],[530,365],[160,390],[500,115]].map(([x,y])=><g key={x} transform={`translate(${x} ${y})`}><circle r="19"/><circle cx="12" cy="-8" r="15"/><circle cx="-10" cy="-10" r="16"/></g>)}</g><text x="45" y="455" fill="#4d5c44" fontSize="14">ARRIVAL COURT</text><text x="540" y="35" fontSize="16" fill="#4d5c44">N ↑</text>{spaces.map((s,i)=><g key={s.name}><circle cx={s.x} cy={s.y} r={space===i?32:22} fill={space===i?"#5d345d":"#fff9ef"} opacity=".95"/><text x={s.x} y={s.y+6} textAnchor="middle" fill={space===i?"#fff":"#5d345d"} fontSize="20">0{i+1}</text></g>)}</svg><div className="lab-map-hotspots">{spaces.map((s,i)=><button key={s.name} style={{left:`${s.x/6}%`,top:`${s.y/4.7}%`}} aria-label={`Explore ${s.name}`} aria-pressed={space===i} onClick={()=>change(()=>setSpace(i))}><span className="lab-sr-only">{s.name}</span></button>)}</div><small>ILLUSTRATIVE MAP / NOT A REAL PROPERTY</small></div>
    <div className="lab-plan-controls"><small>YOUR SETTING</small><h4>{active.name}</h4><p>{active.description}</p><div className="lab-choice-row">{spaces.map((s,i)=><button key={s.name} aria-pressed={space===i} onClick={()=>change(()=>setSpace(i))}>{s.name}</button>)}</div><label htmlFor="lab-guests">Guest count <strong>{guests}</strong></label><input id="lab-guests" type="range" min="20" max="160" step="10" value={guests} onChange={e=>change(()=>setGuests(Number(e.target.value)))}/><button className="lab-weather" aria-pressed={rain} onClick={()=>change(()=>setRain(!rain))}>{rain?"Rain plan on":"Try a rainy day"}</button><div className="lab-plan-result" aria-live="polite"><strong>{!fits?"A little more room needed.":rain&&outdoors?"Bring the ceremony indoors.":"This setting fits your day."}</strong><p>{!fits?`${active.name} holds up to ${active.capacity} demo guests. Explore ${guests<=80?"Glasshouse or Grand hall":"Grand hall"}.`:rain&&outdoors?`Explore ${guests<=80?"Glasshouse":"Grand hall"} for a covered option.`:`${guests} guests / ${active.capacity} capacity. Arrival → ${active.name} → ${space===2?"Dinner & dancing":"Grand hall reception"}.`}</p></div><button className="lab-primary" disabled={!fits||(rain&&outdoors)} onClick={()=>setSaved(true)}>Save this demo plan</button>{saved&&<p role="status">Plan saved in this demonstration. No inquiry sent.</p>}</div></div>
  </div>;
}
function Atelier(){
  const [tone,setTone]=useState("Rose"),[finish,setFinish]=useState("Silver"),[size,setSize]=useState("Desk"),[bag,setBag]=useState<{name:string;price:number}[]>([]);
  const tones:Record<string,string>={Rose:"#e4a8c1",Lavender:"#bca6db",Ink:"#48334f"}; const price=(size==="Desk"?85:145)+(finish==="Gold"?20:0);
  return <div className="lab-atelier lab-world-demo"><div className="lab-demo-title"><small>THE OBJECT ATELIER / CONCEPT COMMERCE</small><h3>Made to <em>your liking.</em></h3><p>A sculptural keepsake, configured as you go. All prices here are fictional product prices.</p></div><div className="lab-experience-grid"><div className="lab-object-stage" style={{backgroundColor:tones[tone]+"55"}}><span>OBJECT No. 01</span><svg viewBox="0 0 400 360" role="img" aria-label={`${tone} heart sculpture with ${finish.toLowerCase()} stand, ${size.toLowerCase()} size`}><defs><linearGradient id="lab-metal"><stop stopColor={finish==="Gold"?"#a07a2e":"#74717b"}/><stop offset=".45" stopColor={finish==="Gold"?"#fff0af":"#fff"}/><stop offset="1" stopColor={finish==="Gold"?"#bd913f":"#9a94a4"}/></linearGradient></defs><ellipse cx="200" cy="317" rx="104" ry="17" fill="#3f2448" opacity=".12"/><g transform={size==="Desk"?"translate(40 40) scale(.8)":"translate(0 0)"}><path d="M200 270V190" stroke="url(#lab-metal)" strokeWidth="18"/><ellipse cx="200" cy="280" rx="70" ry="13" fill="url(#lab-metal)"/><path d="M200 225 C175 197 86 157 89 102 C92 40 172 29 200 81 C233 26 308 43 312 102 C319 155 232 199 200 225Z" fill={tones[tone]} stroke="url(#lab-metal)" strokeWidth="8"/><path d="M117 104 Q118 72 155 66" stroke="#fff" opacity=".65" strokeWidth="9" fill="none" strokeLinecap="round"/></g></svg><em>The heart of the collection.</em></div><div className="lab-plan-controls"><small>SCULPTURAL HEART / DEMO PRODUCT</small><h4>Your little<br/>statement piece.</h4><fieldset><legend>01 / Color</legend><div className="lab-choice-row">{Object.keys(tones).map(t=><button key={t} aria-pressed={tone===t} onClick={()=>setTone(t)}><i style={{background:tones[t]}}/>{t}</button>)}</div></fieldset><fieldset><legend>02 / Finish</legend><div className="lab-choice-row">{["Silver","Gold"].map(f=><button key={f} aria-pressed={finish===f} onClick={()=>setFinish(f)}>{f}{f==="Gold"?" +$20":""}</button>)}</div></fieldset><fieldset><legend>03 / Scale</legend><div className="lab-choice-row">{["Desk","Statement"].map(s=><button key={s} aria-pressed={size===s} onClick={()=>setSize(s)}>{s}</button>)}</div></fieldset><div className="lab-price" aria-live="polite"><strong>${price}</strong><span>{tone} / {finish} / {size}</span></div><button className="lab-primary" disabled={bag.length>=10} onClick={()=>setBag([...bag,{name:`${tone} / ${finish} / ${size}`,price}])}>Add to demo bag</button><div className="lab-demo-bag" aria-live="polite"><strong>Demo bag / {bag.length} {bag.length===1?"object":"objects"}</strong>{bag.map((item,i)=><div key={i}><span>{item.name} · ${item.price}</span><button aria-label={`Remove ${item.name}, item ${i+1}`} onClick={()=>setBag(bag.filter((_,index)=>index!==i))}>Remove</button></div>)}<p>Total ${bag.reduce((sum,item)=>sum+item.price,0)}. No checkout or payment.</p>{bag.length>=10&&<p>Demo bag limit reached. Remove an object to keep exploring.</p>}</div></div></div></div>;
}
function ProjectRoom(){
  const [file,setFile]=useState(""),[approved,setApproved]=useState(false),[note,setNote]=useState(""),[notes,setNotes]=useState<string[]>([]),[delivered,setDelivered]=useState(false);
  const status=delivered?"Delivered":approved?"Ready for delivery":file?"Ready for review":"Waiting for materials";
  return <div className="lab-room lab-world-demo"><div className="lab-demo-title"><small>THE PROJECT ROOM / FICTIONAL CLIENT WORKSPACE</small><h3>From moving parts<br/>to <em>moving forward.</em></h3><p>Try the handoff: add a sample file, leave feedback, approve, then release delivery.</p></div><div className="lab-room-layout"><aside className="lab-room-sidebar"><small>PROJECT No. 024</small><h4>The digital<br/>experience.</h4><strong>{status}</strong><ol>{["Materials","Review","Delivery"].map((s,i)=><li key={s} className={(i===0&&file)||(i===1&&approved)||(i===2&&delivered)?"complete":""}><span>0{i+1}</span>{s}</li>)}</ol><p>A local demonstration. Files, notes, and decisions disappear when you reset or leave.</p></aside><div className="lab-room-main"><div className="lab-room-document"><small>SHARED WORK / VERSION 03</small><h4>A considered<br/><em>first impression.</em></h4><div className="lab-mock-lines"><span/><span/><span/></div><span className="lab-document-seal" aria-hidden="true">A.</span></div><div className="lab-room-actions"><div><h5>01 / Materials</h5><p>{file||"No materials added yet."}</p><button disabled={approved} onClick={()=>setFile("Brand direction.pdf · sample")}>Use sample material</button><label className="lab-file-label">Or choose a local file<input type="file" disabled={approved} onChange={e=>{setFile(e.target.files?.[0]?.name||"");setApproved(false);setDelivered(false)}}/></label><small>Only the filename is read. Nothing is uploaded.</small></div><div><h5>02 / Review</h5><label htmlFor="lab-note">Demo feedback</label><textarea id="lab-note" value={note} onChange={e=>setNote(e.target.value)} maxLength={300} rows={2} disabled={approved}/><button disabled={!note.trim()||approved||notes.length>=5} onClick={()=>{setNotes([...notes,note.trim()]);setNote("")}}>Add local note</button>{notes.map((n,i)=><p className="lab-local-note" key={i}>{n}</p>)}<button disabled={!file||approved} onClick={()=>setApproved(true)}>{approved?"Review approved":"Approve demo review"}</button></div><div><h5>03 / Delivery</h5><p>{!approved?"Available after materials and approval.":delivered?"The demo handoff is complete.":"Approval received. Ready to hand over."}</p><button className="lab-primary" disabled={!approved||delivered} onClick={()=>setDelivered(true)}>Release demo delivery</button><p role="status">{status}</p></div></div></div></div></div>;
}
export default function LabShowroom(){
  const [world,setWorld]=useState(0),[revision,setRevision]=useState(0);
  const current=worlds[world];
  return <section className="lab-showroom" aria-label="Interactive studio showroom"><nav className="lab-world-selector" aria-label="Choose an experience">{worlds.map((w,i)=><button key={w.name} aria-pressed={world===i} onClick={()=>setWorld(i)}><small>{w.label}</small><strong>{w.name}</strong><span>Open experience ↗</span></button>)}</nav><div className="lab-showroom-window"><div className="lab-window-bar"><span> A. HALLIWELL / LIVE CONCEPT No. 0{world+1}</span><button onClick={()=>setRevision(revision+1)} aria-label={`Reset ${current.name}`}>Reset experience ↻</button></div><div key={`${world}-${revision}`}>{world===0?<Estate/>:world===1?<Atelier/>:<ProjectRoom/>}</div><div className="lab-demo-disclosure">LOCAL DEMONSTRATION / No live booking, purchase, upload, approval, or client message.</div></div><div className="lab-capability-caption"><div><small>WHAT THIS MAKES POSSIBLE</small><h3>{current.promise}</h3></div><div><ul>{current.skills.map(s=><li key={s}>{s}</li>)}</ul><p>{current.production}</p><a href="/start">Discuss a system like this ↗</a></div></div></section>;
}
