"use client";
import Image from "next/image";
import { ArrowUpRight } from "@/components/ui/StudioIcons";
import { useId, useRef, useState } from "react";
import { serviceEducation } from "@/lib/lab-engine";
import { BriefLink,Choices,Preview } from "./LabShared";
import RoutingEngine from "./RoutingEngine";
import { consultationSteps } from "@/lib/lab-routing";
const areas=[{name:"Forehead",x:50,y:32,concerns:["Movement lines","Texture","Pigmentation"]},{name:"Under-eye",x:43,y:48,concerns:["Hollowing","Pigment","Fine lines"]},{name:"Cheek",x:65,y:57,concerns:["Volume","Texture","Tone"]},{name:"Lips",x:52,y:67,concerns:["Volume","Definition","Symmetry","Lines around the mouth"]},{name:"Jawline",x:31,y:73,concerns:["Definition","Laxity","Texture"]},{name:"Neck",x:51,y:87,concerns:["Laxity","Texture","Lines"]}];
const bodyAreas={
 Front:[{name:"Upper arms",x:24,y:22,concerns:["Skin texture","Firmness"]},{name:"Abdomen",x:50,y:29,concerns:["Skin texture","Scars","Firmness"]},{name:"Thighs",x:37,y:63,concerns:["Skin texture","Firmness"]}],
 Back:[{name:"Upper arms",x:25,y:21,concerns:["Skin texture","Firmness"]},{name:"Upper back",x:50,y:12,concerns:["Skin texture","Scars"]},{name:"Lower back",x:50,y:28,concerns:["Skin texture","Firmness"]},{name:"Back of thighs",x:38,y:62,concerns:["Skin texture","Firmness"]}]
};
export default function TreatmentArchitect({inHome=false,explorerOnly=false}:{inHome?:boolean;explorerOnly?:boolean}){
 const [educationOpen,setEducationOpen]=useState(false);
 const [routing,setRouting]=useState("");
 const [routingOpen,setRoutingOpen]=useState(false);
 const routingPanelId=useId();
 const routingHeading=useRef<HTMLHeadingElement>(null);
 const openRouting=()=>{setRoutingOpen(true);requestAnimationFrame(()=>routingHeading.current?.focus());};
 const [view,setView]=useState("Face");const [bodySide,setBodySide]=useState<"Front"|"Back">("Front");const [area,setArea]=useState("Jawline");const [concerns,setConcerns]=useState<string[]>([]);const [interests,setInterests]=useState<string[]>([]);const [timeline,setTimeline]=useState("Exploring");const [downtime,setDowntime]=useState("Minimal");const [date,setDate]=useState("");const [service,setService]=useState(0);
 const all=view==="Face"?areas:bodyAreas[bodySide];const active=all.find(a=>a.name===area)||all[0];const education=serviceEducation[service];
 const toggle=(value:string,current:string[],set:(v:string[])=>void)=>set(current.includes(value)?current.filter(v=>v!==value):[...current,value]);
 const demoName=explorerOnly?"Face/Body Concern Explorer":"Treatment Architect / Élan";
 const count=concerns.length+interests.length;
 const image=view==="Face"?"/assets/lab/consultation-face.webp":`/assets/lab/consultation-body-${bodySide.toLowerCase()}.webp`;
 const context=`Discussion priorities: ${[...concerns,...interests].join(", ") || "To discuss"}. Timeline: ${timeline}. Downtime: ${downtime}. ${timeline==="Before an event"?date:""}`;
 return <div className={`lab-experiment lab-treatment medspa-product medspa-explorer ${explorerOnly?"lab-concern-explorer":""}`}>
  <header className="medspa-product-heading"><div><small>{explorerOnly?"FACE / BODY CONCERN EXPLORER":"TREATMENT ARCHITECT / ÉLAN"}</small><h3>Begin with curiosity.<br/><em>Explore your possibilities.</em></h3></div><p>Choose an area. Collect what matters to you. Make space for a more informed conversation.</p></header>
  <div className="medspa-explorer-workspace">
   <div className="medspa-visual-column">
    <div className="medspa-scene-toolbar"><Choices label="Explore areas" options={["Face","Body"]} value={view} onChange={v=>{setView(v);setArea(v==="Face"?"Jawline":bodySide==="Front"?"Abdomen":"Upper back");}}/>{view==="Body"?<Choices label="Body view" options={["Front","Back"]} value={bodySide} onChange={v=>{setBodySide(v as "Front"|"Back");setArea(v==="Front"?"Abdomen":"Upper back");}}/>:null}<span>SELECT AN AREA TO EXPLORE</span></div>
    <div className={`lab-portrait medspa-explorer-scene ${view==="Body"?"lab-body":""}`}>
     <div className="medspa-scene-image medspa-reveal" key={image}><Image src={image} alt={view==="Face"?"Natural portrait used as a selectable facial-area reference":`Headless ${bodySide.toLowerCase()} body photograph in lavender activewear for selecting consultation areas`} width={view==="Face"?612:1024} height={view==="Face"?408:1536} sizes="(max-width:850px) 94vw, 55vw"/>
     {all.map((a,i)=><button type="button" key={a.name} className={`lab-hotspot ${active.name===a.name?"selected":""}`} style={{left:`${a.x}%`,top:`${a.y}%`}} aria-label={`${i + 1} ${a.name}`} aria-pressed={active.name===a.name} onClick={()=>setArea(a.name)}>{i+1}<span>{a.name}</span></button>)}</div>
     <div className="medspa-scene-caption"><small>{view==="Body"?`${bodySide.toUpperCase()} BODY EXPLORATION`:"FACIAL EXPLORATION"}</small><p>Your interests.<br/><em>Your starting point.</em></p></div>
    </div>
    <details className="medspa-area-alternative"><summary>Browse all areas</summary><Choices label="Select an area" options={all.map(a=>a.name)} value={active.name} onChange={setArea}/></details>
   </div>
   <div className="medspa-discovery-panel">
    <section className="medspa-area-discussion medspa-reveal" key={`${view}-${bodySide}-${active.name}`} aria-label="Area discussion"><small>01 / YOUR AREA OF INTEREST</small><h4>{active.name}<em>{view==="Body"?` ${bodySide.toLowerCase()} view`:" Facial exploration"}</em></h4><p>What would you like to discuss? Choose as many topics as you like.</p><div className="medspa-concern-tiles">{active.concerns.map(c=>{const key=`${view==="Body"?`${bodySide} · `:""}${active.name} / ${c}`;return <button key={c} type="button" aria-pressed={concerns.includes(key)} onClick={()=>toggle(key,concerns,setConcerns)}><span>{c}</span><span aria-hidden="true">{concerns.includes(key)?"✓":"+"}</span></button>;})}</div><p className="lab-caption">Discussion topics only. No diagnosis or treatment recommendation.</p></section>
    <section className="medspa-profile" aria-label="Your discussion shortlist"><div className="medspa-profile-title"><small>YOUR DISCUSSION SHORTLIST</small><span role="status">{count} {count===1?"topic":"topics"}</span></div><h4>{count?"A conversation taking shape.":"Start with what matters."}</h4><p>{count?`${concerns.length} area ${concerns.length===1?"concern":"concerns"} and ${interests.length} service ${interests.length===1?"interest":"interests"}, gathered for your consultation.`:"Your selected topics will appear here. Explore freely; you can edit your shortlist at any time."}</p>{count?<details><summary>Review and edit your topics</summary><ul className="lab-profile-list">{concerns.map(c=><li key={c}>{c}<button type="button" onClick={()=>toggle(c,concerns,setConcerns)} aria-label={`Remove ${c}`}>×</button></li>)}{interests.map(c=><li key={c}>Interested in: {c}<button type="button" onClick={()=>toggle(c,interests,setInterests)} aria-label={`Remove ${c}`}>×</button></li>)}</ul></details>:null}
    {!explorerOnly?<button type="button" className="medspa-action" aria-expanded={routingOpen} aria-controls={routingPanelId} disabled={!routingOpen&&!count} onClick={()=>routingOpen?setRoutingOpen(false):openRouting()}>{routingOpen?"Return to visual exploration":"Shape my consultation"}<ArrowUpRight/></button>:null}
    {count?<Preview title="Preview consultation intake"><ul>{[...concerns,...interests.map(s=>`Service interest: ${s}`)].map(s=><li key={s}>{s}</li>)}</ul><p>Timeline: {timeline}{timeline==="Before an event"&&date?` (${date})`:""}. Downtime: {downtime}.</p><p>This organizes your interests. It does not diagnose, prescribe or confirm suitability.</p></Preview>:null}
    </section>
   </div>
  </div>
  <section className="medspa-treatment-library" aria-label="Treatment education"><div className="medspa-section-heading"><div><small>02 / THE TREATMENT LIBRARY</small><h4>Learn before<br/><em>you decide.</em></h4></div><p>Explore services independently of your concerns. A clinician helps you understand what is appropriate for you.</p></div>
   <div className="medspa-treatment-cards">{serviceEducation.map((s,i)=><button key={s.name} type="button" aria-pressed={service===i} aria-controls={`${routingPanelId}-education`} onClick={()=>{setService(i);setEducationOpen(true);}}><div className="medspa-treatment-card-image"><Image src="/assets/lab/consultation-face.webp" alt="" width={612} height={408} sizes="(max-width:520px) 75vw, 280px" style={{objectPosition:["50% 25%","65% 55%","50% 70%","30% 50%","60% 40%"][i]}}/><span>{String(i+1).padStart(2,"0")}</span></div><small>CLINICIAN-LED EDUCATION</small><strong>{s.name}</strong><span className="medspa-card-link">Explore this service <ArrowUpRight/></span></button>)}</div>
   <section id={`${routingPanelId}-education`} hidden={!educationOpen} className="medspa-education-detail medspa-reveal" key={service} aria-label={`${education.name} education`}><div><small>ABOUT THIS SERVICE</small><h4>{education.name}</h4><p>{education.text}</p><a href={education.source} target="_blank" rel="noreferrer">Read the FDA information</a></div><div><button className="medspa-action" type="button" aria-pressed={interests.includes(education.name)} onClick={()=>toggle(education.name,interests,setInterests)}>{interests.includes(education.name)?"Remove service interest":"Add to my discussion topics"}</button><button className="medspa-text-button" type="button" onClick={()=>setEducationOpen(false)}>Close service details</button></div></section>
  </section>
  {!explorerOnly?<section id={routingPanelId} hidden={!routingOpen} className="medspa-consultation-stage" aria-labelledby={`${routingPanelId}-heading`}><small>03 / SHAPE YOUR CONSULTATION</small><h4 id={`${routingPanelId}-heading`} tabIndex={-1} ref={routingHeading}>A thoughtful next step.</h4><details className="medspa-visit-preferences"><summary>Timing & recovery preferences · {timeline} / {downtime}</summary><Choices label="Your timeline" options={["Exploring","Next 3 months","Before an event"]} value={timeline} onChange={setTimeline}/><Choices label="Downtime preference" options={["Minimal","Flexible","Discuss with clinician"]} value={downtime} onChange={setDowntime}/>{timeline==="Before an event"?<label className="lab-field">Event date (optional)<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>:null}</details><RoutingEngine key={[...concerns,...interests].join("|")} steps={consultationSteps} name={demoName} projectType="Beauty / wellness" needs={["Quote or lead flow","Booking or scheduling","Custom interactive feature"]} context={context} disclosure="Your selected preferences route a consultation request. Location, provider credentials, visit format and suitability must be confirmed by the practice. No diagnosis or treatment recommendation." inHome={inHome} onBriefChange={setRouting} presentation="medspa"/></section>:null}
  <footer className="medspa-product-footer"><div><small>WHAT HAPPENS NEXT</small><p>Review your concerns. Discuss options and risks with a clinician. Plan together after an assessment.</p></div><BriefLink publish inHome={inHome} name={demoName} projectType="Beauty / wellness" needs={["Quote or lead flow","Booking or scheduling","Custom interactive feature"]} summary={`${context}\n${routing}`}/></footer><p className="lab-caption">Your demo profile resets when you leave. The project link carries your selected demo context into Start Project. Use fictional preferences here and keep personal medical information out of an AHS project inquiry.</p>
 </div>;
}
