"use client";
import { FormEvent,useMemo,useState } from "react";
type Status="idle"|"sending"|"success"|"error";
const projectTypes=["Small business / service","Hospitality / venue","Beauty / wellness","E-commerce / product brand","Restaurant / nightlife / events","Professional service","Something else"];
const projectNeeds=["One-page website","Multi-page website","Website redesign","E-commerce","Booking or scheduling","Quote or lead flow","Client portal","Events or ticketing","Custom interactive feature","Add to an existing website","Ongoing support"];
const timingOptions=["As soon as possible","Within 2 weeks","Within 3–4 weeks","Within 1–2 months","I'm flexible"];
const investmentOptions=["$1k–$5k","$5k–$10k","$10k–$20k","$20k+","Not sure yet"];

export default function StartProject(){
 const [projectType,setProjectType]=useState(""),[needs,setNeeds]=useState<string[]>([]),[timing,setTiming]=useState(""),[investment,setInvestment]=useState(""),[name,setName]=useState(""),[email,setEmail]=useState(""),[business,setBusiness]=useState(""),[message,setMessage]=useState(""),[website,setWebsite]=useState(""),[status,setStatus]=useState<Status>("idle"),[feedback,setFeedback]=useState("");
 const brief=useMemo(()=>[projectType&&`Business: ${projectType}`,needs.length&&`Needs: ${needs.join(", ")}`,timing&&`Timing: ${timing}`,investment&&`Investment: ${investment}`].filter(Boolean).join("\n"),[projectType,needs,timing,investment]);
 const toggle=(x:string)=>setNeeds(c=>c.includes(x)?c.filter(i=>i!==x):[...c,x]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!projectType||!timing||!investment||!name.trim()||!email.trim()){setStatus("error");setFeedback("Complete the required fields before sending your project.");return}setStatus("sending");try{const r=await fetch("/api/inquiry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,business,projectType,needs,timing,investment,message,website})});const j=await r.json();if(!r.ok||!j.success)throw new Error();setStatus("success");setFeedback("Your project is officially in my inbox. I'll review it and be in touch soon. ♥")}catch{setStatus("error");setFeedback("Your inquiry couldn't be sent right now. Please try again.")}}
 if(status==="success")return <section className="sheet start-sheet" id="start"><div className="start-project start-project-success"><span className="start-kicker">INQUIRY RECEIVED</span><div className="start-success-heart">♥</div><h2>It&apos;s officially<br/>in my inbox.</h2><p>{feedback}</p><div className="start-success-summary"><span>BUSINESS</span><strong>{projectType}</strong><span>INVESTMENT</span><strong>{investment}</strong><span>TIMING</span><strong>{timing}</strong></div></div></section>;
 return <section className="sheet start-sheet" id="start"><div className="start-project"><div className="start-project-header"><div><span className="start-kicker">05 / START A PROJECT</span><h2>What are we<br/>building?</h2></div><p>A one-page site, a full custom build and one missing feature are all valid projects. Tell me what the business needs the internet to do.</p></div><form className="project-builder" onSubmit={submit}>
 <fieldset className="builder-step"><legend><span>01</span>What kind of business is this?</legend><div className="builder-options">{projectTypes.map(x=><button key={x} type="button" className={projectType===x?"selected":""} onClick={()=>setProjectType(x)}>{x}</button>)}</div></fieldset>
 <fieldset className="builder-step"><legend><span>02</span>What do you need?</legend><p className="builder-hint">Choose as many as apply.</p><div className="builder-options">{projectNeeds.map(x=><button key={x} type="button" className={needs.includes(x)?"selected":""} onClick={()=>toggle(x)}>{x}</button>)}</div></fieldset>
 <div className="builder-split"><fieldset className="builder-step"><legend><span>03</span>What&apos;s the timing?</legend><div className="builder-options">{timingOptions.map(x=><button key={x} type="button" className={timing===x?"selected":""} onClick={()=>setTiming(x)}>{x}</button>)}</div></fieldset><fieldset className="builder-step"><legend><span>04</span>What&apos;s the investment?</legend><div className="builder-options">{investmentOptions.map(x=><button key={x} type="button" className={investment===x?"selected":""} onClick={()=>setInvestment(x)}>{x}</button>)}</div></fieldset></div>
 <fieldset className="builder-step builder-contact"><legend><span>05</span>And who am I talking to?</legend><div className="builder-fields"><label><span>Your name <b>*</b></span><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><label><span>Email <b>*</b></span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@business.com"/></label><label><span>Business or brand</span><input value={business} onChange={e=>setBusiness(e.target.value)} placeholder="Business name"/></label><label className="builder-message"><span>What should the website do better?</span><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={6} placeholder="Tell me what you sell, what customers need to do, what already exists, or the feature you wish you had..."/></label><label className="builder-honeypot" aria-hidden="true">Website<input value={website} onChange={e=>setWebsite(e.target.value)} tabIndex={-1}/></label></div></fieldset>
 {brief&&<div className="builder-brief"><span>YOUR PROJECT BRIEF</span><pre>{brief}</pre></div>}
 <div className="builder-submit"><div><small>READY WHEN YOU ARE</small><p>Your answers come directly to A. Halliwell Studio.</p></div><button className="button button-primary" disabled={status==="sending"}>{status==="sending"?"Sending...":"Send my project ↗"}</button></div>
 {feedback&&status==="error"&&<p className="builder-feedback builder-error">{feedback} <a href="mailto:hello@ahalliwellstudio.com">Email the studio directly ↗</a></p>}<p className="builder-privacy">Your information is used only to respond to your project inquiry.</p>
 </form></div></section>
}
